dataset: "/home/joaquintschopp/buckets/b1/datasets/competencia_03_ct.csv"
#dataset: "D:\\Backup DMEYF\\datasets\\competencia_03_ct.csv.gz"

competencia_kaggle: dm-ey-f-2024-tercera

semilla_primigenia: 214363

future:
  - 202109

final_train:
  undersampling: 0.02
  clase_minoritaria:
    - BAJA+1
    - BAJA+2
  training:
    - 202107
    - 202106
    - 202105
    - 202104
    - 202103
    - 202102
    - 202101
    - 202012
    - 202011
    - 202010
    - 202009
    - 202008
    - 202007
    - 202106
    - 202105
    - 202104
    - 202103
    - 202102
    - 202101
    - 201912
    - 201911
    - 201910
    - 201909
    - 201908
    - 201907
    - 201906
    - 201905
    - 201904
    - 201903
    - 201902
    - 201901

train_bo:
  training:
    - 202105
    - 202104
    - 202103
    - 202102
    - 202101
    - 202012
    - 202011
    - 202010
    - 202009
    - 202008
    - 202007
    - 202106
    - 202105
    - 202104
    - 202103
    - 202102
    - 202101
    - 201912
    - 201911
    - 201910
    - 201909
    - 201908
    - 201907
    - 201906
    - 201905
    - 201904
    - 201903
    - 201902
    - 201901
  validation:
    - 202106
  testing:
    - 202107
  undersampling: 0.02
  clase_minoritaria:
    - BAJA+1
    - BAJA+2

lgb_param:
  boosting: gbdt
  objective: binary
  metric: 
    - custom
  boost_from_average: true
  feature_pre_filter: false
  force_row_wise: true
  max_depth: -1
  min_gain_to_split: 0.0
  min_sum_hessian_in_leaf: 0.001
  lambda_l1: 0.0
  lambda_l2: 0.0
  max_bin: 31
  num_iterations: 9999
  bagging_fraction: 1.0
  pos_bagging_fraction: 1.0
  neg_bagging_fraction: 1.0
  is_unbalance: false
  scale_pos_weight: 1.0
  drop_rate: 0.1
  max_drop: 50
  skip_drop: 0.5
  extra_trees: false
  learning_rate: 0.02
  feature_fraction: 0.5
  num_leaves: 200
  min_data_in_leaf: 1000

lgb_param_BO:
  boosting: gbdt
  objective: binary
  metric: 
    - custom
  boost_from_average: true
  feature_pre_filter: false
  force_row_wise: true
  max_depth: -1
  min_gain_to_split: 0.0
  min_sum_hessian_in_leaf: 0.001
  lambda_l1: 0.0
  lambda_l2: 0.0
  max_bin: 31
  num_iterations: 9999
  bagging_fraction: 1.0
  pos_bagging_fraction: 1.0
  neg_bagging_fraction: 1.0
  is_unbalance: false
  scale_pos_weight: 1.0
  drop_rate: 0.1
  max_drop: 50
  skip_drop: 0.5
  extra_trees: false
  learning_rate:
    - 0.02
    - 0.3
  feature_fraction:
    - 0.5
    - 0.9
  num_leaves:
    - 8
    - 2024
  min_data_in_leaf:
    - 100
    - 10000