dataset_train: "D:/DmEyF_Julia/dataset/expw_TS-0002_dataset_train_final.csv"

competencia_kaggle: dm-ey-f-2024-segunda

semilla_primigenia: 214363

dataset_future: "D:/DmEyF_Julia/dataset/expw_TS-0002_dataset_future.csv"


final_train:
  undersampling: 1.0
  clase_minoritaria:
    - BAJA+1
    - BAJA+2
  training:
    - 202106
    - 202105
    - 202104
    - 202103
    - 202102
    - 202101

lgb_param:
  boosting: gbdt
  objective: binary
  metric: 
    - custom
  first_metric_only: true
  boost_from_average: true
  feature_pre_filter: false
  force_row_wise: true
  max_depth: -1
  min_gain_to_split: 0.0
  min_sum_hessian_in_leaf: 0.001
  lambda_l1: 0.0
  lambda_l2: 0.0
  max_bin: 31
  num_iterations: 883
  bagging_fraction: 1.0
  pos_bagging_fraction: 1.0
  neg_bagging_fraction: 1.0
  is_unbalance: false
  scale_pos_weight: 1.0
  drop_rate: 0.1
  max_drop: 50
  skip_drop: 0.5
  extra_trees: false
  learning_rate: 0.0200390867108235
  feature_fraction: 0.626739200380393
  num_leaves: 1195
  min_data_in_leaf: 7811

lgb_param_BO:
  learning_rate:
    - 0.02
    - 0.3
  feature_fraction:
    - 0.5
    - 0.9
  num_leaves:
    - 8
    - 2024
  min_data_in_leaf:
    - 100
    - 10000